openapi: "3.0.0"
info:
  description: "API per la gestione delle prenotazioni alberghiere."
  version: "1.0.0"
  title: "Sistema di Gestione Alberghiera"
servers:
  - url: http://localhost/REST/server
paths:
  /ospiti:
    get:
      tags:
      - "ospite"
      summary: "Ottiene una lista di tutti gli ospiti"
      description: "Restituisce tutti gli ospiti"
      responses:
        '200':
          description: "Una lista di ospiti"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Ospite'
    post:
      tags:
      - "ospite"
      summary: "Crea un nuovo ospite"
      description: "Aggiunge un nuovo ospite al sistema"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ospite'
      responses:
        '201':
          description: "Ospite creato"
        '400':
          description: "Dati invalidi"
  /ospiti/{ID_Ospite}:
    get:
      tags:
      - "ospite"
      summary: "Trova ospite per ID"
      description: "Restituisce un singolo ospite"
      parameters:
      - name: "ID_Ospite"
        in: "path"
        description: "ID dell'ospite da restituire"
        required: true
        schema:
          type: "integer"
      responses:
        '200':
          description: "Ospite restituito con successo"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ospite'
        '404':
          description: "Ospite non trovato"
    put:
      tags:
      - "ospite"
      summary: "Aggiorna un ospite esistente"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ospite'
      responses:
        '200':
          description: "Ospite aggiornato con successo"
        '404':
          description: "Ospite non trovato"
    delete:
      tags:
      - "ospite"
      summary: "Elimina un ospite"
      responses:
        '200':
          description: "Ospite eliminato"
        '404':
          description: "Ospite non trovato"
components:
  schemas:
    Ospite:
      type: "object"
      required:
      - "Nome"
      - "Cognome"
      - "Email"
      properties:
        ID_Ospite:
          type: "integer"
          format: "int64"
        Nome:
          type: "string"
        Cognome:
          type: "string"
        Email:
          type: "string"
