openapi: "3.0.0"
info:
  description: "API per la gestione degli account."
  version: "1.0.0"
  title: "Sistema di Gestione Account"
servers:
  - url: http://localhost/server/Server.php
paths:
  /accounts:
    get:
      tags:
      - "account"
      summary: "Ottiene una lista di tutti gli account"
      description: "Restituisce tutti gli account"
      responses:
        '200':
          description: "Una lista di account"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Account'
    post:
      tags:
      - "account"
      summary: "Crea un nuovo account"
      description: "Aggiunge un nuovo account al sistema"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountInput'
      responses:
        '201':
          description: "Account creato"
        '400':
          description: "Dati invalidi"

    put:
      tags:
      - "account"
      summary: "Aggiorna un account esistente"
      description: "Aggiorna le informazioni di un account esistente"
      parameters:
      - name: "ID_Account"
        in: "path"
        description: "ID dell'account da aggiornare"
        required: true
        schema:
          type: "integer"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountUpdate'
      responses:
        '200':
          description: "Account aggiornato con successo"
        '404':
          description: "Account non trovato"
    delete:
      tags:
      - "account"
      summary: "Elimina un account"
      description: "Elimina un account esistente dal sistema"
      parameters:
      - name: "ID_Account"
        in: "path"
        description: "ID dell'account da eliminare"
        required: true
        schema:
          type: "integer"
      responses:
        '200':
          description: "Account eliminato"
        '404':
          description: "Account non trovato"
components:
  schemas:
    Account:
      type: "object"
      required:
      - "ID_Account"
      - "Email"
      - "Nome"
      - "Cognome"
      properties:
        ID_Account:
          type: "integer"
          format: "int64"
        Email:
          type: "string"
        Nome:
          type: "string"
        Cognome:
          type: "string"
        Password:
          type: "string"
          format: "password"
    AccountInput:
      type: "object"
      required:
      - "Email"
      - "Password"
      - "Nome"
      - "Cognome"
      properties:
        Email:
          type: "string"
        Password:
          type: "string"
          format: "password"
        Nome:
          type: "string"
        Cognome:
          type: "string"
    AccountUpdate:
      type: "object"
      required:
      - "Email"
      properties:
        Email:
          type: "string"
